method = 'copy'
plugin_dirs = [
    '/home/michael/.vst/Windows',
    '/home/michael/.vst3/Windows',
]
no_verify = false
blacklist = []

[last_known_config]
wine_version = 'wine-7.8 (Staging)'
yabridge_host_hash = 3576984302002065197
